# Generated by Django 5.0 on 2024-11-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messagesmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('time', models.DateField(verbose_name='زمان')),
                ('message', models.TextField(max_length=10000, verbose_name='متن پیام')),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویداد ها',
            },
        ),
    ]
