# Generated by Django 5.0 on 2024-12-03 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messagesModel", "0003_alter_messagesmodel_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="messagesmodel",
            name="type",
            field=models.IntegerField(
                choices=[(1, "اعلان"), (2, "هشدار"), (3, "خطر"), (4, "رویداد")],
                default=1,
                verbose_name="نوع اعلان",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="messagesmodel",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
