# Generated by Django 5.0 on 2024-12-03 12:02

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messagesModel", "0004_messagesmodel_type_messagesmodel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagesmodel",
            name="title",
            field=models.CharField(
                default="hello", max_length=200, verbose_name="عنوان پیام"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="messagesmodel",
            name="message",
            field=models.TextField(
                blank=True, max_length=10000, null=True, verbose_name="متن پیام"
            ),
        ),
        migrations.AlterField(
            model_name="messagesmodel",
            name="time",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="زمان"
            ),
        ),
    ]
