# Generated by Django 5.0 on 2025-02-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_karjomodelproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('desc', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('image', models.ImageField(help_text='بنر با طول تمام صفحه قرار حواهد گرفت.', upload_to='', verbose_name='عکس تبلیغ')),
                ('link', models.CharField(max_length=1000, verbose_name='لینک تبلیغ')),
            ],
            options={
                'verbose_name': 'تبلیغات ویژه',
                'verbose_name_plural': 'تبلیغات ویژه',
            },
        ),
    ]
