# Generated by Django 5.0 on 2024-11-19 16:15

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repotageModel', '__first__'),
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('show', models.IntegerField(choices=[(0, 'دیده نشده'), (1, 'دیده شده')], default=0, verbose_name='وضغیت مشاهده')),
                ('acsept', models.IntegerField(choices=[(0, 'قبول نشده'), (1, 'قبول شده')], default=0, verbose_name='وضعیت قبولی')),
                ('desc', ckeditor.fields.RichTextField()),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ مصاحب')),
                ('repotage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repotageModel.repotagemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.karjomodel')),
            ],
            options={
                'verbose_name': 'رزومه',
                'verbose_name_plural': 'رزومه ها',
            },
        ),
    ]
