# Generated by Django 5.0 on 2024-11-23 09:31

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resomeModel', '0002_alter_resomemodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resomemodel',
            name='datetime',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ مصاحب'),
        ),
    ]
