# Generated by Django 5.0 on 2024-11-24 09:17

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repotageModel', '0005_alter_repotagemodel_created_at_and_more'),
        ('resomeModel', '0004_remove_resomemodel_acsept_resomemodel_status_and_more'),
        ('user', '0005_alter_karfarmamodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resomemodel',
            name='desc',
            field=ckeditor.fields.RichTextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='resomemodel',
            name='repotage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repotageModel.repotagemodel', verbose_name='پروژه'),
        ),
        migrations.AlterField(
            model_name='resomemodel',
            name='show',
            field=models.IntegerField(choices=[(0, 'رد'), (1, 'تایید')], default=0, verbose_name='تایید یا رد'),
        ),
        migrations.AlterField(
            model_name='resomemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.karjomodel', verbose_name='کاربر'),
        ),
    ]
