# Generated by Django 5.0 on 2024-11-19 16:15

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته بندی ')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='WriterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('name', models.CharField(max_length=100, verbose_name='نام نویسنده')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسنده ها',
            },
        ),
        migrations.CreateModel(
            name='Blogsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('image', models.ImageField(upload_to='static/blogsPhoto', verbose_name='عکس بلاگ')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام بلاگ')),
                ('desc', models.TextField(blank=True, max_length=100000, null=True, verbose_name='چکیده ')),
                ('blogText', ckeditor.fields.RichTextField(verbose_name='توضیحات بلاگ')),
                ('better', models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی')),
                ('readTime', models.IntegerField(help_text='\n        با تنظیم این مقدار به شکل دقیقه میتوانید مخاطبین را به \n        وبلاگ خاص سوق دهید', verbose_name='زمان خواندن')),
                ('catgegory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='blogsModel.categorymodel', verbose_name='دسته بندی')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogsModel.writermodel', verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ ها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('name', models.CharField(max_length=100, verbose_name='نام نویسنده نظر')),
                ('email', models.CharField(max_length=100, verbose_name='ایمیل نویسنده نظر')),
                ('desc', models.TextField(max_length=100000, verbose_name='متن نظر')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogsModel.blogsmodel')),
            ],
            options={
                'verbose_name': 'کامت',
                'verbose_name_plural': 'کامت ها',
            },
        ),
    ]
