# Generated by Django 5.0 on 2024-11-19 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('phone', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(9000000000)], verbose_name='شماره تماس')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('dec', models.CharField(max_length=10000, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
            },
        ),
    ]
