# Generated by Django 5.0 on 2024-11-19 16:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('name', models.CharField(max_length=100, verbose_name='نام شهر')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهر ها',
            },
        ),
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('name', models.CharField(max_length=50, verbose_name='نام شخص')),
                ('phone', models.IntegerField(validators=[django.core.validators.RegexValidator(regex='^(?:0|98|98|980|0098|098|00980)?(9\\d{9})$')], verbose_name='شماره تماس')),
            ],
            options={
                'verbose_name': 'شخص',
                'verbose_name_plural': 'اشخاص',
            },
        ),
        migrations.CreateModel(
            name='Drugstoresmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('name', models.CharField(max_length=100, verbose_name='نام داروخانه')),
                ('desc', models.TextField(blank=True, max_length=100, null=True, verbose_name='توضیحات')),
                ('phone1', models.IntegerField(validators=[django.core.validators.RegexValidator(regex='^(?:0|98|98|980|0098|098|00980)?(9\\d{9})$')], verbose_name='شماره تماس')),
                ('phone2', models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(regex='^(?:0|98|98|980|0098|098|00980)?(9\\d{9})$')], verbose_name='شماره تماس')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugstoresModel.citymodel', verbose_name='شهر')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugstoresModel.personmodel', verbose_name='شخص')),
            ],
            options={
                'verbose_name': 'داروخانه',
                'verbose_name_plural': 'داروخانه ها',
            },
        ),
    ]
