# Generated by Django 5.0 on 2025-01-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugstoresModel', '0003_alter_drugstoresmodel_phone1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugstoresmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='drug/image', verbose_name='لوگو داروخانه'),
        ),
    ]
