# Generated by Django 5.0 on 2024-11-23 09:31

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_allusers_created_at_alter_allusers_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karjomodel',
            name='birthdate',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ تولد'),
        ),
    ]
