# Generated by Django 5.0 on 2024-11-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_karjomodel_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karfarmamodel',
            name='date',
            field=models.DateField(null=True, verbose_name='تاریخ تاسیس'),
        ),
    ]
