# Generated by Django 5.0 on 2024-12-16 04:23

import django.core.validators
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_karfarmamodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karfarmamodel',
            name='phoneMajazi',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(9000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='شماره تلفن مجازی'),
        ),
        migrations.AlterField(
            model_name='karjomodel',
            name='badBack',
            field=models.IntegerField(blank=True, choices=[(0, 'خیر'), (1, 'بله')], null=True, verbose_name='آیا دارای گواهی عدم سو پیشینه هستید ؟'),
        ),
        migrations.AlterField(
            model_name='karjomodel',
            name='birthdate',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='karjomodel',
            name='certificate',
            field=models.IntegerField(blank=True, choices=[(0, 'خیر'), (1, 'بله')], null=True, verbose_name='آیا دارای گواهی مرتبط هستید ؟'),
        ),
        migrations.AlterField(
            model_name='karjomodel',
            name='education',
            field=models.IntegerField(blank=True, choices=[(0, 'دانشجو'), (1, 'سیکل'), (2, 'دیپلم'), (3, 'کارشناسی'), (4, 'ارشد'), (5, 'دکتری')], null=True, verbose_name='وضعیت تحصیلات'),
        ),
        migrations.AlterField(
            model_name='karjomodel',
            name='knowType',
            field=models.IntegerField(blank=True, choices=[(0, 'معرف'), (1, 'در داروخانه'), (2, 'گوگل')], null=True, verbose_name='نحوه\u200cی آشنایی با سایت'),
        ),
        migrations.AlterField(
            model_name='karjomodel',
            name='meliNo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='karjomodel',
            name='nezam',
            field=models.IntegerField(blank=True, choices=[(0, 'معاف'), (1, 'مشمول'), (2, 'پایان خدمت')], null=True, verbose_name='وضعیت نظام وظیفه'),
        ),
        migrations.AlterField(
            model_name='karjomodel',
            name='program',
            field=models.IntegerField(blank=True, choices=[(0, 'ایمن افزار شایگان'), (1, 'قانون فارما'), (2, 'فارماسی'), (3, 'دارو پردازان'), (4, 'ماندگار'), (5, 'وکیل')], null=True, verbose_name='در صورت آشنایی با نرم\u200cافزار مرتبط، آن را انتخاب کنید '),
        ),
        migrations.AlterField(
            model_name='karjomodel',
            name='retrain',
            field=models.IntegerField(blank=True, choices=[(0, 'خیر'), (1, 'بله')], null=True, verbose_name='آیا دارای ساعات بازآموزی معتبر هستید ؟'),
        ),
        migrations.AlterField(
            model_name='karjomodel',
            name='technisian',
            field=models.IntegerField(blank=True, choices=[(0, 'خیر'), (1, 'بله')], null=True, verbose_name='آیا دارای گواهی تکنسین دارویی یا آرایشی بهداشتی هستید ؟ '),
        ),
        migrations.AlterField(
            model_name='karjomodel',
            name='worked',
            field=models.IntegerField(blank=True, choices=[(0, 'خیر'), (1, 'بله')], null=True, verbose_name='آیا سابقه کار دارید؟'),
        ),
    ]
