# Generated by Django 5.0 on 2024-12-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_karfarmamodel_phonemajazi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='karjomodel',
            name='nezam_file',
            field=models.FileField(blank=True, null=True, upload_to='static/nezam_file_file', verbose_name='کارت نظام وظیفه'),
        ),
        migrations.AlterField(
            model_name='karjomodel',
            name='gender',
            field=models.IntegerField(choices=[(0, 'زن'), (1, 'مرد')], verbose_name='جنسیت'),
        ),
    ]
