# Generated by Django 5.0 on 2024-12-16 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_karjomodel_nezam_file_alter_karjomodel_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karjomodel',
            old_name='technisian',
            new_name='technician',
        ),
    ]
