# Generated by Django 5.0 on 2024-12-16 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_technisian_karjomodel_technician'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karjomodel',
            old_name='technisian_file',
            new_name='technician_file',
        ),
    ]
