# Generated by Django 5.0 on 2024-12-16 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_technisian_file_karjomodel_technician_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karjomodel',
            old_name='logo',
            new_name='profilePicture',
        ),
        migrations.RemoveField(
            model_name='karjomodel',
            name='banner',
        ),
    ]
