# Generated by Django 5.0 on 2024-11-19 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repotagemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('gender', models.IntegerField(choices=[(0, 'مونث'), (1, 'مذکر'), (2, 'بدون اهمیت')], verbose_name='جنسیت')),
                ('title', models.IntegerField(choices=[(1, 'تکنسین داروخانه'), (2, 'تکنسین آرایشی بهداشتی'), (3, 'صندوقدار'), (4, 'انبار دار'), (5, 'مسئول فنی'), (6, 'قائم مقام'), (7, 'کارآموز دارویی'), (8, 'کار آموز آرایشی و بهداشتی')], verbose_name='عنوان')),
                ('nameMotabar', models.IntegerField(choices=[(0, 'دارد'), (1, 'ندارد'), (2, 'بدون اهمیت')], verbose_name='نامه معتبر از دانشگاه')),
                ('nezam', models.IntegerField(choices=[(0, 'دارد'), (1, 'ندارد'), (2, 'بدون اهمیت')], verbose_name='کارت نظام')),
                ('saatHamkari', models.IntegerField(choices=[(0, 'تمام وقت'), (1, 'نیمه وقت'), (2, 'پاره وقت')], verbose_name='ساعت همکاری')),
                ('desc', models.TextField(max_length=100, verbose_name='توضیحات')),
                ('show', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی')),
                ('long', models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی')),
                ('price', models.CharField(max_length=100, verbose_name='قیمت')),
                ('fori', models.BooleanField(default=False, verbose_name='فوری')),
                ('fromKarfarma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.karfarmamodel', verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'اگهی',
                'verbose_name_plural': 'اگهی ها',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('name', models.CharField(max_length=100, verbose_name='نام تگ')),
                ('repotage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repotageModel.repotagemodel', verbose_name='آگهی مرتبط')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
