# Generated by Django 5.0 on 2024-11-20 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repotageModel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repotagemodel',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='repotagemodel',
            name='long',
        ),
    ]
