# Generated by Django 5.0 on 2024-11-20 13:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repotageModel', '0003_alter_tagmodel_options_alter_repotagemodel_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repotagemodel',
            name='desc',
            field=ckeditor.fields.RichTextField(verbose_name='توضیحات بلاگ'),
        ),
    ]
